### ISSUE TITLE
Report potential bugs with "Right" and "B"

### ISSUE THREAD

**Issue by huskydoge** [rafaelcp/smbdataset#2]
After I texted the actions onto the corresponding frames, made them into a video, and watched a few cases, I found that "right" actually records for the "B" button event, and "B" records the "Right" button event.

**Comment by rafaelcp** [comment]
That's probably a problem in the getAction function. In my tests, the order was always the same (or I hope so), so I didn't notice any issue, but Lua tables, as most hashtable implementations, don't guarantee order. The solution would be to loop through a fixed list of button names (in the same order as stated in the readme) instead of looping through 'buttons' directly. I can't work on it right now, but I'll leave the possible solutions here in case you want to fix it yourself, or for my future self to fix it when I have the time: [https://stackoverflow.com/questions/19260423/how-to-keep-the-order-of-a-lua-table-with-string-keys](https://stackoverflow.com/questions/19260423/how-to-keep-the-order-of-a-lua-table-with-string-keys)

Thanks for pointing that out.

**Comment by rafaelcp** [comment]
BTW, did you test on your own recordings or in the repo dataset? I assumed it was the first case, but if it was the second, then my second question is: was this button swap consistent among all frames? If yes, than I can just change the readme and swap those 2 buttons. If it wasn't consistent, then I really messed up!

**Comment by huskydoge** [comment]
Thanks for your reply. I tested on the repo dataset, and I found this consistent among all the frames. Those examples (already swapped) look good to me  now:https://drive.google.com/drive/folders/1okATwleSrlKlWmG9fCbPHigvArCWKKZu

**Comment by rafaelcp** [comment]
There is still something weird there: when you show 'up' it is actually 'A'. When you show 'down', it is actually 'up'. When you show 'start', it is actually 'down'.

For debugging, the single buttons in decimal are: select = 1, start = 2, B = 4, A = 8, right = 16, left = 32, down = 64, up = 128. Just add'em up to get combinations. Does it match the numbers in the filenames?

**Comment by rafaelcp** [comment]
I just checked the filenames and they're all swapped indeed! It shows 64 while climbing the beanstalk in 2-1, which should be up, but is documented as down.

**Comment by rafaelcp** [comment]
The correct encoding seems to be:

start, select = 1 or 8, dunno which
down = 2 (when you enter a pipe)
right = 4
B = 16 (run and/or fire)
left = 32
up = 64 (climb)
A = 128 (jump)

Does it make more sense to you?

**Comment by huskydoge** [comment]
Opus! Thanks for letting me know, otherwise I will feed my model with the wrong actions labeled. 🙏

To be honest, I'm not familiar with the Mario game, so I only find the "right" "b" are swapped. Let me update my code according to your comment and see.

**Comment by huskydoge** [comment]
@rafaelcp Yes I think everything is good now, thanks!
